sonar.projectKey=dynamic-data-exporter
sonar.projectName=dynamic-data-importer
sonar.projectVersion=1.0

sonar.sources=apps/demo-symfony/src,packages/cli-adapter/src,packages/core/src,packages/doctrine-adapter/src,packages/symfony-adapter/src
sonar.tests=apps/demo-symfony/tests,packages/cli-adapter/tests,packages/core/tests,packages/doctrine-adapter/tests,packages/symfony-adapter/tests

sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=phpunit-report.xml

sonar.exclusions=vendor/**,var/**,node_modules/**
