framework:
    secret: '%env(default:this_is_not_secret:APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    default_locale: de
    enabled_locales: ['de', 'en']

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    validation: { enabled: true }
    csrf_protection: { enabled: true }
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - de

    messenger:
        transports:
            async_imports: 'filequeue://async_imports'
        routing:
            'App\Message\RunImportMessage': async_imports
